### ISSUE TITLE
Remove secrets from source code

### ISSUE THREAD

**Issue by daakulov** [denisyakimov07/Discord_BOT#2]
https://github.com/denisyakimov07/Discord_BOT/blob/ec7d085c79cf197818e4bee163296f8620e596df/config.py#L5

Please look into static code analysis: https://www.perforce.com/blog/sca/what-static-analysis 
You can find open source static code analysis tools for python. Use them!

**Comment by denisyakimov07** [comment]
All keys and tokens was change and put to os environment variable
